version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13
        user: root
        environment:
          GAE_VERSION: 1.9.55
          GOPATH: /go/
          BASH_ENV: ./circleci_bashenv
    working_directory: /go/
    steps:
      - checkout
      - run:
          name: Install Google App Engine
          command: |
            pushd /usr/local/bin/
            if [ ! -d "./go_appengine" ]; then
              wget "https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-${GAE_VERSION}.zip" -nv
              unzip -q "go_appengine_sdk_linux_amd64-${GAE_VERSION}.zip"
            fi
            popd
      - run:
          name: Install dep
          command: |
            cd src/app/aeloader
            goapp get -u github.com/golang/dep/cmd/dep
      - run:
          name: Get vendor
          command: |
            cd src/app
            dep ensure
      - run:
          name: Run tests
          command: |
            cd src/app
            goapp test $(goapp list ./... | grep -v /vendor/)
